New beaker helper `bolt_supported` to show bolt availability
voxpupuli/beaker_puppet_helpers pull request #42
Opened 2024-04-28 20:16 UTC by traylenator

Can be used in `spec/spec_helper_acceptance.rb` as:

```ruby
if bolt_supported(host)
  host.install_package('puppet-bolt')
end
```

bolt_supported returns `true` or `false` depending on if a bolt package is available for a particular platform.

2024-04-28 20:26 UTC, ekohl approved these changes
It didn't occur to me to implement this in the support library but I think it makes sense. One question: it doesn't take the Puppet version into account. We have that mostly encoded in puppet_metadata. What do you think about that relationship?

2024-04-28 20:50 UTC, traylenator commented
> One question: it doesn't take the Puppet version into account. We have that mostly encoded in puppet_metadata. What do you think about that relationship?

There must be a fairly circular dependency between Puppet, Bolt and puppetlab- modules that means bolt and puppet existence must be in close lock. Think I'd worry about it if it happens.... or we know it does happen.

2024-04-29 15:07 UTC, ekohl requested changes
I suppose it's safe to assume they publish Bolt for Puppet 7 & 8 on a given platform. If they don't, then we'll cross that bridge once we get there.

2024-04-29 15:07 UTC, ekohl commented on lib/beaker_puppet_helpers/dsl.rb
> +    def bolt_supported(host = default)
Should we indicate it's a boolean?
```suggestion
    def bolt_supported?(host = default)
```

2024-04-29 15:07 UTC, ekohl commented on lib/beaker_puppet_helpers/dsl.rb
> +    # @return Boolean True if package is available.
This needs to be 
```suggestion
    # @return [Boolean] True if package is available.
```

Or, if you follow the suggestion below it's implicit
```suggestion
    # @return True if package is available.
```

And yes, I also just noticed that for `fact_on` it's also wrong.

2024-04-29 15:07 UTC, ekohl commented on lib/beaker_puppet_helpers/dsl.rb
I'm debating if it should be in `InstallUtils`. Did you consider this too?

2024-04-29 15:13 UTC, traylenator commented on lib/beaker_puppet_helpers/dsl.rb
I did it in InstallUtils  first in fact but thought the:

```
if ...::InstallUtils::bolt_supported(host)
  host.install_package('puppet-bolt')
end
```
was a bit ugly.... Also was not sure if you could then use in the tests themselves as per:

https://github.com/voxpupuli/puppet-redis/pull/521/files#diff-3298d5e0d4c7c6e7d2d02e74da28191589ec62021af821fb4116df556ef88daeR12

2024-04-30 08:10 UTC, ekohl approved these changes
CI is still running, but looks good

2024-04-30 08:50 UTC, merged