rubocop: autofix / rubocop: Use rubocop-rspec & rubocop-rake
voxpupuli/beaker_puppet_helpers pull request #6
Opened 2023-03-31 12:17 UTC by bastelfreak

2023-04-01 14:17 UTC, ekohl requested changes
Some cops have been fixed and https://github.com/voxpupuli/beaker_puppet_helpers/pull/13 will fix more.

2023-04-02 14:03 UTC, bastelfreak commented on beaker_puppet_helpers.gemspec
> +  # Testing dependencies
@ekohl should we add those 4 gems as runtime deps to beaker? Then we don't need to list them in each beaker plugin.

2023-04-28 12:19 UTC, ekohl commented
@bastelfreak should we update this to https://github.com/voxpupuli/voxpupuli-rubocop?

2023-04-28 12:22 UTC, bastelfreak commented
yes,will do

2023-04-28 15:58 UTC, ekohl reviewed
I'm kind of leaning to disabling the cops that are in TODO.

2023-04-28 15:58 UTC, ekohl commented on .rubocop_todo.yml
> +RSpec/SubjectStub:
I don't know how else to test the DSL so I think this should just be disabled.

2023-04-28 15:58 UTC, ekohl commented on .rubocop_todo.yml
> +RSpec/RepeatedDescription:
Legitimate problem: https://github.com/voxpupuli/beaker_puppet_helpers/pull/18

2023-04-28 15:58 UTC, ekohl commented on Rakefile
> +  RuboCop::RakeTask.new(:rubocop) do |task|
Given the repetition, should we have some wrapper in voxpupuli-rubocop?

2023-04-28 16:09 UTC, bastelfreak commented on Rakefile
> +  RuboCop::RakeTask.new(:rubocop) do |task|
we have, but in a other PR you didnt like :D voxpupuli-rubocop defines the rake task and we could include that.

2023-05-05 18:20 UTC, bastelfreak commented on Rakefile
> +  RuboCop::RakeTask.new(:rubocop) do |task|
I added https://github.com/voxpupuli/voxpupuli-rubocop/blob/master/lib/voxpupuli/rubocop/rake.rb . I'm also happy for other ideas but I also think that's something that could be improved in the future.

2023-05-05 18:21 UTC, bastelfreak commented on .rubocop_todo.yml
> +RSpec/SubjectStub:
disabled it

2023-05-05 18:23 UTC, ekohl commented on .rubocop_todo.yml
> +RSpec/StubbedMock:
I think we should also disable this.

2023-05-05 18:23 UTC, ekohl commented on beaker_puppet_helpers.gemspec
> +  s.add_development_dependency 'voxpupuli-rubocop', '~> 1.2'
Can we declare this in the Gemfile where it was previously defined?

2023-05-05 18:23 UTC, ekohl commented on Rakefile
> +  RuboCop::RakeTask.new(:rubocop) do |task|
Let's just use that then.

2023-05-05 18:39 UTC, bastelfreak commented on beaker_puppet_helpers.gemspec
> +  s.add_development_dependency 'voxpupuli-rubocop', '~> 1.2'
done

2023-05-05 18:40 UTC, bastelfreak commented on .rubocop_todo.yml
> +RSpec/StubbedMock:
done

2023-05-05 18:50 UTC, bastelfreak commented on Rakefile
> +  RuboCop::RakeTask.new(:rubocop) do |task|
done

2023-05-05 19:00 UTC, ekohl commented on Gemfile
> +  gem 'voxpupuli-rubocop', '~> 1.2'
Any reason not to have a rubocop group anymore?

2023-05-05 19:00 UTC, ekohl commented on Rakefile
> +require 'voxpupuli/rubocop/rake'
Can you add a begin/rescue around it so `BUNDLE_WITHOUT=development` still allows you to run the tests?

2023-05-05 19:05 UTC, bastelfreak commented on Gemfile
> +  gem 'voxpupuli-rubocop', '~> 1.2'
moved it to its own group

2023-05-05 19:05 UTC, bastelfreak commented on Rakefile
> +require 'voxpupuli/rubocop/rake'
done

2023-05-05 20:11 UTC, merged